<h3>Your Privacy</h3>

<p>Privacy is important. This website does <strong>NOT</strong> require or collect any personally identifiable information.</p>

<p>Here's a full disclosure of all privacy related information on this site.</p>

<h5>Passwords</h5>

<p><b>
Because we do not collect your email address, there is NO PASSWORD RESET FUNCTIONALITY.
If you lose your password, you will lose access to your account, period.
</b></p>

<p>Passwords are hashed using the industry-standard bcrypt algorithm. For those curious about the technicalities, we're currently using a "cost" of 12, to make it computationally unrealistic to perform any sort of brute force attempt to crack the passwords. <b>This also means the site owner/admin does not and cannot know what your password is.</b></p>

<h5>Browser Cookies</h3>

<p>You will have two browser cookies set by this website.</p>

<ul>
    <li>PHPSESSID — This cookie is how we keep you logged in. It simply contains a unique token that's used for authentication.</li>
    <li>IO — This cookie is set by the websocket library we use to make sure chat messages arrive instantly. The library is called socket.io, and the cookie it sets is also just a unique token with no personal information.</li>
</ul>

<p>Setting these two cookies are required for the functionality of this website.</p>

<h5>IP Addresses</h3>

<p>Our application itself does not record your IP address at any time. While great for privacy this has the unfortunate side-effect of making it significantly more difficult to detect when accounts have been compromised. So pick a strong password!</p>

<p>While our <em>application</em> does not record IP addresses, our webserver, nginx currently does. In the near future, we may change the nginx log format to exclude IP's, and this section will be updated to reflect that. Our websever access logs are currently only retained for 24 hours.</p>




