<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="refresh" content="3">
    <link rel="stylesheet" href="/mdl/material.indigo-pink.min.css">
    <link rel="stylesheet" href="/roboto/roboto.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script defer src="/mdl/material.min.js"></script>
    <style>
        h3, p { text-align: center; }
        .mdl-spinner {
            display: block;
            margin: 25px auto;
        }

    </style>
</head>
<body>
    <h3>This image is still being uploaded...</h3>
    <div class="mdl-spinner mdl-spinner--single-color mdl-js-spinner is-active"></div>
    <p>(Or the upload was cancelled or failed, in which case this page will never load.)</p>
</body>
</html>
