<style>
form, .mdl-button, .mdl-textfield {
    width: 100%;
}
</style>
<div class="mdl-grid" style="width: 340px;">

    <form method="post" action="<?= $this->url('auth-login') ?>" autocomplete="off">
    <div class="mdl-cell mdl-cell--12-col">
        <h5>Login</h5>
    </div>



    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="username" name="username">
        <label class="mdl-textfield__label" for="username">Username</label>
      </div>
    </div>


    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="password" id="password" name="password">
        <label class="mdl-textfield__label" for="password">Password</label>
      </div>
    </div>


    <input type="hidden" name="__csrf_value" value="<?= $this->csrfToken() ?>">


    <div class="mdl-cell mdl-cell--12-col">
        <button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">
          Login
        </button>
    </div>
</form>
</div>
